# coding: utf-8

"""
    BOMIST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class WorkspaceExport(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ws_path': 'str',
        'dest_path': 'str'
    }

    attribute_map = {
        'ws_path': 'wsPath',
        'dest_path': 'destPath'
    }

    def __init__(self, ws_path=None, dest_path=None):  # noqa: E501
        """WorkspaceExport - a model defined in Swagger"""  # noqa: E501

        self._ws_path = None
        self._dest_path = None
        self.discriminator = None

        if ws_path is not None:
            self.ws_path = ws_path
        self.dest_path = dest_path

    @property
    def ws_path(self):
        """Gets the ws_path of this WorkspaceExport.  # noqa: E501

        Workspace folder (contains a workspace.bomist_ws file in it) - if not passed, the current workspace's path is used  # noqa: E501

        :return: The ws_path of this WorkspaceExport.  # noqa: E501
        :rtype: str
        """
        return self._ws_path

    @ws_path.setter
    def ws_path(self, ws_path):
        """Sets the ws_path of this WorkspaceExport.

        Workspace folder (contains a workspace.bomist_ws file in it) - if not passed, the current workspace's path is used  # noqa: E501

        :param ws_path: The ws_path of this WorkspaceExport.  # noqa: E501
        :type: str
        """

        self._ws_path = ws_path

    @property
    def dest_path(self):
        """Gets the dest_path of this WorkspaceExport.  # noqa: E501

        Destination absolute path (must contain the filename with a .bomist_dump extension). On windows backslashes must be escaped.  # noqa: E501

        :return: The dest_path of this WorkspaceExport.  # noqa: E501
        :rtype: str
        """
        return self._dest_path

    @dest_path.setter
    def dest_path(self, dest_path):
        """Sets the dest_path of this WorkspaceExport.

        Destination absolute path (must contain the filename with a .bomist_dump extension). On windows backslashes must be escaped.  # noqa: E501

        :param dest_path: The dest_path of this WorkspaceExport.  # noqa: E501
        :type: str
        """
        if dest_path is None:
            raise ValueError("Invalid value for `dest_path`, must not be `None`")  # noqa: E501

        self._dest_path = dest_path

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WorkspaceExport, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WorkspaceExport):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
